version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-laravel-app
    container_name: my-laravel-container 
    command: php artisan serve --host=0.0.0.0 --port=9000
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - db


  db:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel_db
      MYSQL_PASSWORD: password
    ports:
      - "3301:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
