version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-laravel-app
    container_name: my-laravel-container 
    command: php artisan serve --host=0.0.0.0 --port=9000
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - db


  db:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel_db
      MYSQL_PASSWORD: password
    ports:
      - "3301:3306"
    volumes:
      - mysql-data:/var/lib/mysql



  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_DB: blog
      POSTGRES_USER: root 
      POSTGRES_PASSWORD: password 




  pgadmin:
      image: dpage/pgadmin4
      container_name: pgAdmin
      ports:
        - "5051:80"
      depends_on:
        - db 
      environment:
        PGADMIN_DEFAULT_EMAIL: youremail@gmail.com
        PGADMIN_DEFAULT_PASSWORD: password 

# networks:
#   laravel-network:
#     driver: bridge
# change the env file to your desired value
# DB_CONNECTION=pgsql
# DB_HOST=db
# DB_PORT=5432
# DB_DATABASE=blog
# DB_USERNAME=same_as_of_the_yml file(postgres service)
# DB_PASSWORD=same_as_of_the_yml file(postgres service)